name: Release
on:
  push:
    tags:
      - '*'
jobs:
  build:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Use Node 21.x
        uses: actions/setup-node@v4
        with:
          node-version: 21.x

      - name: Install deps and build (with cache)
        uses: bahmutov/npm-install@v1

      - name: Setup environment for publishing
        run: sh scripts/setup-for-publishing.sh

      - name: Publish ${{ github.ref_name }}
        env:
          VERSION: ${{ github.ref_name }}
        run: npm run deploy
